### PR TITLE
first attempts at supporting v0.12

### PR DESCRIPTION
**Pull request by davidmarkclements**
So this doesn't work with Node v0.12 - I've made attempts at fixing but out of my depth in C++ (willing to learn though!). 

So it seems the first step would be to upgrade nan to 1.6 - this actually works great (with some deprecation warnings.)

The next problem was atomicops.h - in v8 3.27 (node  v0.12 is on v8 3.28) 
this was relocated to deps/v8/src/base, and then atomicops.h is expecting deps/v8.

So that's why extra paths are added to bindings.gyp.

Then I hit these errors:

``` sh
In file included from ../src/v8_flags.cc:111:
../src/v8_flag_definitions.h:4:1: error: C++ requires a type specifier for all declarations
DEFINE_BOOL(use_strict, false, "enforce strict mode")
^~~~~~~~~~~
../src/v8_flag_definitions.h:4:13: error: use of undeclared identifier 'use_strict'
DEFINE_BOOL(use_strict, false, "enforce strict mode")
            ^
../src/v8_flag_definitions.h:4:54: error: expected ';' after top level declarator
DEFINE_BOOL(use_strict, false, "enforce strict mode")
```

And now I do not know what to do...

I notice scripts/preinstall.js performs some pre-processing on the flags definition file... 

Maybe there's been a refactor of v8_flag_definitions.h  ... 

... help?

### CODE REVIEW

**Comment by thlorenz** [comment]
Thanks for taking the time to look into this. I didn't expect this to be so complex to do :(
NaN upgrade and extra path are fine.

WRT errors, I'm not sure if this is due to the fact that node 0.12 uses different C++ flags to support C11 or if something changed about the v8_flag_definitions.h.
When I wrote this originally I made sure that things worked with [these](https://github.com/thlorenz/v8-flags/tree/master/v8).

So maybe we could diff [this one](https://github.com/thlorenz/v8-flags/blob/master/v8/flag-definitions.3.25.30.h) against the newer one?
That may also reveal a change that broke the [preinstall script](https://github.com/thlorenz/v8-flags/blob/master/scripts/preinstall.js) since that highly depends on the structure of that file.

LMK if you need any help I'd love to have this work for node 0.12 and io.js.
Thanks.

**Comment by davidmarkclements** [comment]
Yah I totally need help, I'm not proficient in C - what if we break this into investigative tasks and split them between us?

**Comment by thlorenz** [comment]
I cannot guarantee you that I'll have time to look into this seriously any time soon.
How would you like to split it?
